# Generated by Django 3.2.9 on 2024-09-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
